name: ZIVPN Native Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildAPK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Manual Clone Mihomo Core
        run: |
          mkdir -p core/src/foss/golang/
          rm -rf core/src/foss/golang/clash
          git clone --depth 1 -b Meta https://github.com/MetaCubeX/mihomo core/src/foss/golang/clash

      - name: Download Geo Assets
        run: |
          mkdir -p service/src/main/assets
          wget -O service/src/main/assets/GeoIP.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
          wget -O service/src/main/assets/GeoSite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
          ls -lh service/src/main/assets/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go Mod Tidy
        run: |
          cd core/src/foss/golang
          go mod tidy
          cd ../../../main/golang
          go mod tidy

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK (Alpha Release)
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleAlphaRelease --stacktrace

      - name: Upload ZIVPN Native APK (Arm64)
        uses: actions/upload-artifact@v4
        with:
          name: ZIVPN-Native-Arm64-APK
          path: app/build/outputs/apk/alpha/release/*-arm64-v8a-*.apk

      - name: Upload ZIVPN Native APK (Armv7)
        uses: actions/upload-artifact@v4
        with:
          name: ZIVPN-Native-Armv7-APK
          path: app/build/outputs/apk/alpha/release/*-armeabi-v7a-*.apk

      - name: Upload ZIVPN Native APK (Universal)
        uses: actions/upload-artifact@v4
        with:
          name: ZIVPN-Native-Universal-APK
          path: app/build/outputs/apk/alpha/release/*-universal-*.apk
