name: ZIVPN Native Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildAPK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Versi Go yang direkomendasikan untuk Mihomo Alpha

      - name: Manual Clone Mihomo Core
        run: |
          mkdir -p core/src/foss/golang/
          rm -rf core/src/foss/golang/clash
          git clone --depth 1 -b Alpha https://github.com/MetaCubeX/mihomo core/src/foss/golang/clash
          # Perbaikan: Sinkronisasi dependency Go agar tidak error 'go mod tidy'
          cd core/src/foss/golang/clash
          go mod tidy

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK (Armv7a Only)
        run: |
          chmod +x gradlew
          # -PabiList=armeabi-v7a digunakan untuk memfilter arsitektur build
          ./gradlew :app:assembleAlphaRelease -PabiList=armeabi-v7a --stacktrace

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZIVPN-Native-Armv7a
          path: app/build/outputs/apk/alpha/release/*.apk
          retention-days: 7 # File akan tersimpan selama 7 hari di artefak
